name: C Simplify Library CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make

      - name: Install MinGW manually
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "Downloading MinGW..."
          curl -L -o mingw.7z https://github.com/niXman/mingw-builds-binaries/releases/download/15.2.0-rt_v13-rev0/x86_64-15.2.0-release-posix-seh-ucrt-rt_v13-rev0.7z
          7z x mingw.7z -oC:/mingw64 > /dev/null
          echo "Adding MinGW to PATH"
          echo "C:/mingw64/mingw64/bin" >> $GITHUB_PATH

      - name: Verify GCC
        run: gcc --version

      - name: Build project
        run: |
          make clean
          make all

      - name: Run tests
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ./test/run.exe || exit 1
          else
            ./test/run || exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            lib/libsimplify.a
            test/run*
